Add map api route
yuanjian-org/app pull request #325
Opened 2024-08-14 20:31 UTC by UncleBu1728

Added `map.ts` under `map/route` containing the skeleton of the routers. This initial implementation includes the router structure without any functions implemented.

2024-08-15 02:27 UTC, weihanwang commented on src/api/map/routes/map.ts
> +  .use(authUser("Mentee"||"Mentor"))
no need for "Mentee"||"Mentor". every logged-in user should be able to use the map.

2024-08-15 02:27 UTC, weihanwang commented on src/api/map/routes/map.ts
> +const list = procedure
let's start with this single API function and remove all others. let's implement map reading end-to-end first before moving on to updating etc.

2024-08-15 02:27 UTC, weihanwang commented on src/api/map/routes/map.ts
> +  .query(async () =>
can you write out input parameters and return type?

2024-08-15 17:25 UTC, UncleBu1728 commented
Vercel is showing errors due to the Eslint rules. Do we need another PR to disable these rules for now? Or work on more API implementation?
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/32226fec-d82f-43ce-8e85-c875a5b1a096">

2024-08-16 01:25 UTC, weihanwang requested changes

2024-08-16 01:25 UTC, weihanwang commented on src/api/map/routes/map.ts
> +  .input(z.string())
an enum type should be explicitly defined. refer to the Role type.

2024-08-16 01:25 UTC, weihanwang commented on src/api/map/routes/map.ts
> +  .output(z.array(z.object({})))
a struct type should be explicitly defined, with fields like ”定义“、“进阶” etc.

2024-08-18 00:19 UTC, weihanwang commented on src/api/map/routes/map.ts
> +const zLandmark = z.object({
this needs to be in a folder referencable by the front end.

2024-08-18 00:19 UTC, weihanwang commented on src/api/map/routes/map.ts
> +  .input(z.object({
the input doesn't need any of these fields. it instead needs lattitude which should be an enum.

2024-08-18 00:19 UTC, weihanwang commented on src/api/map/routes/map.ts
> +  纬度: z.string(),
These should be enums

2024-08-18 00:19 UTC, weihanwang commented on src/api/map/routes/map.ts
> +  工具箱: z.string(),
this should be optional().

2024-08-18 00:19 UTC, weihanwang commented on src/api/map/routes/map.ts
> +  相关地标: z.array(z.string()),
this should be optional

2024-08-19 22:33 UTC, weihanwang requested changes

2024-08-19 22:33 UTC, weihanwang commented on src/shared/Map.ts
> +export const Longtitude = [
`Longtitudes`

2024-08-19 22:33 UTC, weihanwang commented on src/shared/Map.ts
> +export const Latitude = [
ditto

2024-08-19 23:30 UTC, weihanwang commented on src/shared/Map.ts
> +export const zLongtitudes = z.enum(Longtitudes);
keep it as `zLongtitude`. singular.

2024-08-19 23:30 UTC, weihanwang commented on src/shared/Map.ts
> +export const zLatitudes = z.enum(Latitudes);
ditto.

2024-08-20 05:15 UTC, weihanwang commented on src/api/map/routes/map.ts
> +/* eslint-disable require-await */
Use per-line statement and not per-file. Move them to immediately above the lines where lint rules are violated.

2024-08-20 05:41 UTC, weihanwang approved these changes

2024-08-20 05:41 UTC, merged