Add AssessorId to LandmarkAssessment Table
yuanjian-org/app pull request #387
Opened 2024-09-30 20:35 UTC by UncleBu1728

Add `assessorId` in `LandmarkAssessment`to allow permitted users to access specific Landmark assessment histories.

2024-10-01 00:02 UTC, weihanwang approved these changes

2024-10-01 00:02 UTC, weihanwang requested changes
assessorId can't be null

2024-10-01 16:19 UTC, UncleBu1728 commented
> assessorId can't be null

Does it mean we must assign a mentor to the record whenever we submit a landmark assessment?

2024-10-02 00:57 UTC, weihanwang commented
Yes. the assessor of self assessments is the current user.

2024-10-02 17:10 UTC, weihanwang submitted a review, later dismissed

2024-10-02 17:52 UTC, UncleBu1728 commented
`@BelongsTo` is used instead of `@HasOne` in order to associate assessor with User model using assessorId. Otherwise, an error would be shown as below:

"throw new Error(`Foreign key for "${relatedClass.name}" is missing ` +
              ^Error: Foreign key for "LandmarkAssessment" is missing on "user"."

2024-10-03 16:06 UTC, weihanwang commented on src/api/database/models/User.ts
> +  landmarkAssessments: LandmarkAssessment[];
Don't add it for now. Let's add it only when we actual need it.

2024-10-03 16:06 UTC, weihanwang commented on src/api/database/models/map/LandmarkAssessment.ts
> +  assessorId: string | null;
make a comment about what null means.

2024-10-03 18:04 UTC, weihanwang commented on src/api/database/models/User.ts
> +import LandmarkAssessment from "./map/LandmarkAssessment";
remove this

2024-10-03 18:04 UTC, weihanwang commented on src/api/database/models/map/LandmarkAssessment.ts
> +  // If assessorId (assessor) is null, the landmark assessment is self-evaluated by the user;
is this line > 80 chars long?

2024-10-03 18:22 UTC, merged